### PR TITLE
Self-shadowing feature 

### LINKED ISSUE #320: [BUG]: Estimation tools do not support segment-fixed panels
### Describe the issue:

The panelled radiation pressure partial is computed by looping over the total number of panels, but can only access body-fixed panels. This causes the propagation to crash and throws an out-of-bounds error.

### How to reproduce the issue:

By setting the vehicle shape to include a segment-fixed panel, and consequently trying to estimate some parameters, it is possible to reproduce the bug.
```
body_tracking = environment_setup.vehicle_systems.body_tracking_panel_geometry('Sun', True, 10)
body_tracking_panel = environment_setup.vehicle_systems.body_panel_settings(body_tracking, environment_setup.radiation_pressure.specular_diffuse_body_panel_reflection(0.4, 0.4, True))
frame_variable = environment_setup.vehicle_systems.frame_fixed_panel_geometry(np.array([1, 0, 0]), 10, 'part')
part_rot_sett = environment_setup.rotation_model.spice(
        'J2000','J2000',  "")
dict_rotation_settings = {"part": part_rot_sett}
frame_variable_panel = environment_setup.vehicle_systems.body_panel_settings(frame_variable, environment_setup.radiation_pressure.specular_diffuse_body_panel_reflection(0.4, 0.4, True))

body_settings.get('vehicle').vehicle_shape_settings = environment_setup.vehicle_systems.full_panelled_body_settings([body_tracking_panel, frame_variable_panel], dict_rotation_settings)
```

### OS:

OS: Linux, Windows

### Expected behavior:

No error messages

### Current behavior:

```
vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Error, propagation terminated at t=757694592.000000, returning propagation data up to current time.
```

### Additional context:

The issue lies in tudat\src\astro\orbit_determination\acceleration_partials\panelledRadiationPressureAccelerationPartial.cpp, where:
```
 for( int i = 0; i < panelledTargetModel_->getTotalNumberOfPanels( ); i++ )
       { 
          currentPanelPartialContribution.setZero( );
          if( panelledTargetModel_->getBodyFixedPanels( ).at( i )->getTrackedBody( ) != acceleratingBody_ )
```
the code loops over the total number of panels and tries to access the bodyFixedPanels vector (which comprises body-fixed and body-tracking only) out of its bounds when segment-fixed panels are present.

### PR DESCRIPTION
**Pull request by nikemais**
This PR adds the self-shadowing (SSH) algorithm and multiple supporting features:

- Loading macro-model from COLLADA (.dae) file from Blender after defining the geometry and assigning materials to each panel;
- Assembling multiple parts while still allowing to define rotation setting for each part;
- New dependent variable to save the fractions of illuminated panels, querying by panel material ID;
- Simple unit test for SSH with required file added to data.zip.

The parallel PR in tudatpy exposes this feature and comes with documentation.

This is my very first PR, so all help and suggestions are more than welcome!

### CODE REVIEW

File: include/tudat/simulation/environment_setup/createRadiationPressureTargetModel.h [hunk 1]
```diff
@@ -122,6 +122,26 @@ class CannonballRadiationPressureTargetModelSettings : public RadiationPressureT
...
+
+class PaneledRadiationPressureTargetModelSettings : public RadiationPressureTargetModelSettings
+{
+private:
+    int maximumNumberOfPixels_;
+
+public:
+    explicit PaneledRadiationPressureTargetModelSettings(
+        const std::map< std::string, std::vector< std::string > >& sourceToTargetOccultingBodies = { },
+        int maximumNumberOfPixels = 0):
```
Comment (DominicDirkx) [inline include/tudat/simulation/environment_setup/createRadiationPressureTargetModel.h:134]: maximumNumberOfPixels = 0 meaning no shadowing? For internal settings, this is fine, but the user interface should be slightly different, with either:
* An interface to create a model without shadowing
* A boolean to set to False

File: src/astro/electromagnetism/radiationPressureTargetModel.cpp [hunk 2]
```diff
@@ -82,51 +83,88 @@ void PaneledRadiationPressureTargetModel::updateRadiationPressureForcing( double
...
+    {
+        throw std::runtime_error("Error: maximum number of pixels must be positive and at least 2!");
+    }
+    if ( maximumNumberOfPixels_ == 1 )
+    {
+        if ( macroModelLoaded_ )
+        {
+            throw std::runtime_error("Error: maximum number of pixels must be at least two!");
+        }
+        if ( !macroModelLoaded_ )
```
Comment (DominicDirkx) [inline src/astro/electromagnetism/radiationPressureTargetModel.cpp:116]: I'd recommend handling this separately from the maximumNumberOfPixels_==1 check. Have a separate

if( maximumNumberOfPixels_ > 0 && !macroModelLoaded_ )

Also, this check can be made in the constructor once, rather than repeatedly in the inner loop (?)

File: include/tudat/astro/electromagnetism/radiationPressureTargetModel.h [hunk 3]
```diff
@@ -341,6 +362,22 @@ class PaneledRadiationPressureTargetModel : public RadiationPressureTargetModel
 
     void saveLocalComputations( const std::string sourceName, const bool saveCosines ) override;
 
+    bool isMacroModelLoaded( ) const
+    {
+        return macroModelLoaded_;
+    }
+
+    std::vector< double > getIlluminatedPanelFractions( ) const
```
Comment (DominicDirkx) [inline include/tudat/astro/electromagnetism/radiationPressureTargetModel.h:370]: make std::vector< double >& to prevent copying of large array

File: include/tudat/astro/system_models/geometryUtils.h [hunk 4]
```diff
@@ -0,0 +1,201 @@
+/*    Copyright (c) 2010-2019, Delft University of Technology
+*    All rigths reserved
+*
+*    This file is part of the Tudat. Redistribution and use in source and
+*    binary forms, with or without modification, are permitted exclusively
+*    under the terms of the Modified BSD license. You should have received
+*    a copy of the license with this file. If not, please or visit:
+*    http://tudat.tudelft.nl/LICENSE.
+*/
+#ifndef TUDAT_GEOMETRYUTILS_H
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/geometryUtils.h:10]: Please use 'verbose' naming (so panelGeometryUtilities rather than geometryUtils)

File: include/tudat/astro/system_models/geometryUtils.h [hunk 5]
```diff
@@ -0,0 +1,201 @@
...
+*    All rigths reserved
+*
+*    This file is part of the Tudat. Redistribution and use in source and
+*    binary forms, with or without modification, are permitted exclusively
+*    under the terms of the Modified BSD license. You should have received
+*    a copy of the license with this file. If not, please or visit:
+*    http://tudat.tudelft.nl/LICENSE.
+*/
+#ifndef TUDAT_GEOMETRYUTILS_H
+#define TUDAT_GEOMETRYUTILS_H
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/geometryUtils.h:11]: Could you add some in-code comments to this file?

File: include/tudat/astro/system_models/geometryUtils.h [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+    
+public:
+    ParallelProjection( ):  minCoordinateL_( 0.0 ), maxCoordinateL_( 0.0 ), minCoordinateM_( 0.0 ), maxCoordinateM_( 0.0 ),
+                            triangle2d_( ), lambdas_( )
+    { }
+
+    ParallelProjection( const Triangle3d& triangle, const Triangle3d& triangleToBeProjected, 
+                        const Eigen::Vector3d& projectionDirection_= Eigen::Vector3d::Zero( ) )
+    {
+        Eigen::Vector3d dummyDirection = Eigen::Vector3d::Zero( );
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/geometryUtils.h:124]: why define as a separate variable (and not instantiate directly where it is used?)

File: include/tudat/astro/system_models/geometryUtils.h [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+   Eigen::Vector3d getVersorM( ) const
+   {
+       return versorM_;
+   }
+};
+
+class ParallelProjection
+{
+private:
+    double minCoordinateL_, maxCoordinateL_, minCoordinateM_, maxCoordinateM_;
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/geometryUtils.h:112]: min-> minimum
max-> maximum

Do 'L' and 'M' and 'lambda' have a physical/geometrical meaning that can be used for the naming?

File: include/tudat/astro/system_models/selfShadowing.h [hunk 8]
```diff
@@ -0,0 +1,491 @@
...
+#include "tudat/astro/system_models/geometryUtils.h"
+#include "tudat/astro/system_models/vehicleExteriorPanels.h"
+
+namespace tudat
+{
+
+namespace system_models
+{
+
+inline bool firstDiscrimination( const std::shared_ptr< system_models::VehicleExteriorPanel > panel,
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/selfShadowing.h:28]: Could you move these inline functions to the .cpp? It can save on computation time (and is better practice)

File: include/tudat/astro/system_models/selfShadowing.h [hunk 9]
```diff
@@ -0,0 +1,491 @@
+/*    Copyright (c) 2010-2019, Delft University of Technology
+*    All rigths reserved
+*
+*    This file is part of the Tudat. Redistribution and use in source and
+*    binary forms, with or without modification, are permitted exclusively
+*    under the terms of the Modified BSD license. You should have received
+*    a copy of the license with this file. If not, please or visit:
+*    http://tudat.tudelft.nl/LICENSE.
+*/
+#ifndef TUDAT_SELFSHADOWING_H
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/selfShadowing.h:10]: Could you add references to the relevant equations in literature you implement here (to at least make clear how/which algorithm is implemented)?

File: include/tudat/astro/system_models/selfShadowing.h [hunk 10]
```diff
@@ -0,0 +1,491 @@
...
+        int numberOfPanels = allPanels.size( );
+        // initialize sigma matrix for discrimination logic (-2 dummy value, -1 no-sh, 0 partial sh, 1 full sh)
+        std::vector<std::vector< int >> sigmaMatrix(numberOfPanels, std::vector< int >(numberOfPanels, -2));
+        // first discrimination
+        std::vector< int > firstDiscriminationIndexes;
+        for (int i = 0; i < numberOfPanels; i++) {
+            if ( !firstDiscrimination( allPanels[i], incomingDirection ) ){
+                firstDiscriminationIndexes.push_back( i );
+                for (int j = 0; j < numberOfPanels; j++) {
+                    sigmaMatrix[j][i] = -1; // cannot shadow other plates
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/selfShadowing.h:312]: for accessing std::vector elements, used .at( i ) rather than [i]. Using [i] can lead to memory corruption/segfaults if used out of bounds.

File: src/astro/electromagnetism/radiationPressureTargetModel.cpp [hunk 11]
```diff
@@ -82,51 +83,88 @@ void PaneledRadiationPressureTargetModel::updateRadiationPressureForcing( double
...
+        }
+    }
+    if ( maximumNumberOfPixels_ >= 2 )
+    {
+        if ( !macroModelLoaded_ )
+        {
+            throw std::runtime_error("Error: maximum number of pixels given but macro-model is not loaded!");
+        }
+        // compute illuminated fractions with SSH algorithm
+        selfShadowing_ = system_models::SelfShadowing( allRotatedPanels_, sourceToTargetDirectionLocalFrame, maximumNumberOfPixels_ );
```
Comment (DominicDirkx) [inline src/astro/electromagnetism/radiationPressureTargetModel.cpp:128]: Rather than re-creating the object every time, I'd recommend modifying this so that the same selfShadowing_ object is used in every call. Creating/destroying the object every time can incur significant memory overhead

File: include/tudat/astro/system_models/selfShadowing.h [hunk 12]
```diff
@@ -0,0 +1,491 @@
...
+}
+
+class SelfShadowing
+{
+private:
+    std::vector< double > illuminatedPanelFractions_;
+public:
+    SelfShadowing( ) : illuminatedPanelFractions_( ) { };
+
+    SelfShadowing( const std::vector< std::shared_ptr< system_models::VehicleExteriorPanel > >& allPanels,
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/selfShadowing.h:298]: Try to break this functionality up into sub-functions, to make the code easier to read/maintain

File: include/tudat/astro/system_models/selfShadowing.h [hunk 13]
```diff
@@ -0,0 +1,491 @@
...
+                         projection.getMaxL( ) <= allPanels[i]->getSelfProjection( ).getMinL( ) || 
+                         projection.getMinM( ) >= allPanels[i]->getSelfProjection( ).getMaxM( ) ||
+                         projection.getMaxM( ) <= allPanels[i]->getSelfProjection( ).getMinM( ) )
+                    {
+                        sigmaMatrix[i][j] = -1; // no-sh
+                    }
+                    else
+                    {
+                        // second test: use PIP algorithms
+                        std::vector< bool > shadowingInShadowed = isTriangleInTriangle( allPanels[i]->getSelfProjection( ),
```
Comment (DominicDirkx) [inline include/tudat/astro/system_models/selfShadowing.h:375]: if possible, prevent initializing an array inside a for loop

**Comment by DominicDirkx** [comment]
Hi Niccolo, I've added a whole bunch of comments/questions to your code. In the nature of doing this, I've only written points where I think some things should be made different, but overall I don't think any of these changes are very invasive. You've written a very impressive piece of code here, I'm really looking forward to getting it merged!

**Comment by nikemais** [comment]
### TODOs:

- [x] SSH user interface: new logic and functionalities
- [x] Naming verbosity (files and variables)
- [x] ParallelProjection minor change
- [x] SSH code efficiency
- [x] Code commenting improvements
- [x] Vector element access (switch from `[ i ]` to `.at( i )` )

File: include/tudat/simulation/environment_setup/createRadiationPressureTargetModel.h [hunk 14]
```diff
@@ -122,6 +122,26 @@ class CannonballRadiationPressureTargetModelSettings : public RadiationPressureT
...
+std::map< std::string, int > maximumNumberOfPixelsPerSource_;
+
+public:
+    explicit PaneledRadiationPressureTargetModelSettings(
+        const std::map< std::string, std::vector< std::string > >& sourceToTargetOccultingBodies = { },
+        const std::map< std::string, int > maximumNumberOfPixelsPerSource = { } ):
+    RadiationPressureTargetModelSettings( RadiationPressureTargetModelType::paneled_target, sourceToTargetOccultingBodies ),
+    maximumNumberOfPixelsPerSource_( maximumNumberOfPixelsPerSource )
+    { }
+
```
Comment (nikemais) [inline include/tudat/simulation/environment_setup/createRadiationPressureTargetModel.h:138]: New user interface: dictionary of maximum number of pixels per source, if one source is left, it is assumed SSH is turned off. This results in a more flexible management of SSH for different sources, previously unavailable.

File: src/astro/electromagnetism/radiationPressureTargetModel.cpp [hunk 15]
```diff
@@ -71,62 +106,54 @@ void PaneledRadiationPressureTargetModel::updateRadiationPressureForcing( double
...
+        illuminatedPanelFractions_ = std::vector< double >( totalNumberOfPanels_, 1.0);
+    }
+    else
     {
-        currentOrientation = Eigen::Quaterniond( Eigen::Matrix3d::Identity( ) );
-        if( i > 0 )
+        // SSH on
+        selfShadowingPerSource_.at( sourceName )->updateIlluminatedPanelFractions( sourceToTargetDirectionLocalFrame );
+        illuminatedPanelFractions_ = selfShadowingPerSource_.at( sourceName )->getIlluminatedPanelFractions( );
+    }
```
Comment (nikemais) [inline src/astro/electromagnetism/radiationPressureTargetModel.cpp]: To avoid creating a new object in the loop, the same object is updated using the new updateIlluminatedpanelFractions member function.

**Comment by nikemais** [comment]
Hi Dominic, I have made some changes to the code, two parts are highlighted in the comments above: the new user interface (which showcases the possibility to customise SSH for different sources) and the new updateIlluminatedPanelFractions (one of the many changes implemented to optimise the code). 

Overall, I have added comments and references where necessary, and I have also indicated that most of the explanations, tailored to this implementation, will be present in my thesis report.

Furthermore, the fix to the issue with the partial computation is also included (this means this PR closes #320). Let me know if further actions are required!

**Comment by DominicDirkx** [comment]
I merged the data.zip file for the tests, unit tests now running

**Comment by DominicDirkx** [comment]
I resolved the test file conflict. Now I see there's quite a few unit test failures:
https://github.com/tudat-team/tudat/actions/runs/15115795909/job/42486034768?pr=309
Some of them may be resolved by this:
https://github.com/tudat-team/tudat/pull/321
But, before I merge it, could you check if you get one (or more) of the same failures locally?

**Comment by nikemais** [comment]
I am currently working on it. I think the issue might actually be in #321, as the fix is already included in this PR. 
The common error is:
`std::out_of_range: map::at`
which might be related to the new interface for SSH settings (a map of pixels for each source).

**Comment by DominicDirkx** [comment]
If you merge #321 into this branch (or, make any push to this branch for that matter, the CI will automatically retrigger)

**Comment by DominicDirkx** [comment]
Awesome, well done! Just to check: are the interfaces backwards compatible and is the associated tudatpy PR up-to-date with this one?

File: src/astro/orbit_determination/acceleration_partials/panelledRadiationPressureAccelerationPartial.cpp [hunk 16]
```diff
@@ -40,11 +40,26 @@ void PanelledRadiationPressurePartial::update( const double currentTime )
...
+            {   
+                // SSH off
+                illuminatedPanelFractions = std::vector< double >( allPanels.size( ), 1.0);
+            }
+            else
+            {
+                // SSH on
+                selfShadowingPerSource.at( acceleratingBody_ )->updateIlluminatedPanelFractions( -bodyFixedUnitVectorToSource );
+                illuminatedPanelFractions = selfShadowingPerSource.at( acceleratingBody_ )->getIlluminatedPanelFractions( );
+            }
```
Comment (nikemais) [inline src/astro/orbit_determination/acceleration_partials/panelledRadiationPressureAccelerationPartial.cpp]: This is required if the partials are computed without first computing the acceleration, which means skipping the update function for illuminatedPanelFractions. This is the same step from the updateRadiationPressureForcing function from radiationPressureTargetModel.cpp.

Comment (DominicDirkx) [reply src/astro/orbit_determination/acceleration_partials/panelledRadiationPressureAccelerationPartial.cpp]: Can you list one (or more) unit tests that failed when this code was not there?

Comment (nikemais) [reply src/astro/orbit_determination/acceleration_partials/panelledRadiationPressureAccelerationPartial.cpp]: tests/src/astro/orbit_determination/acceleration_partials/unitTestAccelerationPartials.cpp
tests/src/astro/orbit_determination/unitTestRadiationPressureEstimation.cpp

**Comment by DominicDirkx** [comment]
Merging! @nikemais Could you open an issue addressing the computational efficiency enhancements to make to this code?
