### PR TITLE
Tudat-specific exceptions

### LINKED ISSUE #296: Raise Tudat-specific errors
At the moment Tudat does not implement custom errors for internal errors.
E.g. when using the [LagrangeInterpolatorBoundaryHandling.lagrange_no_boundary_interpolation](https://py.api.tudat.space/en/latest/interpolators.html#tudatpy.math.interpolators.LagrangeInterpolatorBoundaryHandling), a generic python RuntimeError is raised, making it undistinguishable if the error occurred due to interpolation inside the unreliable interval or due to own implementation error.

It would be nice to have Tudat-specific errors that could be caught inside `try... except...` blocks to handle such situations robustly.

### PR DESCRIPTION
**Pull request by larshinueber**
This draft PR adds custom exceptions for tudat to allow for a more granular exception handling.

All exceptions inherit from a generic `TudatError`, which itself inherits from `std::runtime_error`, which seems to be the default exception in the tudat codebase. This should make the changes backwards compatible, as any `try{...} catch( std::runtime_error const& ){...}` block should still catch the derived exceptions.

At the moment, custom exceptions have been added for all tudatpy functions, where throwing an exception is an explicitly user-defined behavior (interpolation boundary handling, root finder iterations, integration step size validation). If desired, this could be generalized in the future and used throughout the codebase.

A companion PR is open on the tudatpy-side: https://github.com/tudat-team/tudatpy/pull/250

Since this is my first C++ contribution, any feedback both on the coding style and the feature itself is appreciated :)

# TODO:
- [x] Add C++ documentation
- [x] Add unit tests (what should be tested?)

### CODE REVIEW

**Comment by larshinueber** [comment]
That's a great point, thank you!
I suspect the error message could be assembled from the arguments in the constructor of the derived classes and then be used as input to the constructor of the base class? Will look into it the next days 👍

**Comment by larshinueber** [comment]
A quick note for future reference: It seems it is more complicated to expose the exception class attributes than expected.
The attributes of the exception class cannot simply be exposed using the same syntax as class attributes, e.g.
```cpp
    auto interpolationOutOfBoundsErrorExp =
            py::register_exception< te::InterpolationOutOfBoundsError< TIME_TYPE > >(
                    m, "InterpolationOutOfBoundsError", tudatErrorExp.ptr( ) )
                    .def_property_readonly( "requestedValue",
                                            &te::InterpolationOutOfBoundsError< TIME_TYPE >::requestedValue,
                                            "The value of the independent variable requested by the user." );
```

throws
```
/home/lars/repos/tudat-bundle/tudatpy/tudatpy/kernel/expose_exceptions.cpp:37:22: error: ‘class pybind11::exception<tudat::exceptions::InterpolationOutOfBoundsError<double> >’ has no member named ‘def_property_readonly’
   37 |                     .def_property_readonly( "requestedValue",
      |                      ^~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [tudatpy/tudatpy/CMakeFiles/kernel.dir/build.make:286: tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_exceptions.cpp.o] Error 1
```

There is a workaround, which involves defining the Python exception class manually and then translating the C++ exception to a Python exception, see https://github.com/pybind/pybind11/issues/1281 and in particular https://github.com/pybind/pybind11/issues/1281#issuecomment-1815721395.

**Comment by larshinueber** [comment]
A first working exposure is now implemented in https://github.com/tudat-team/tudatpy/pull/250.

As described in the proposed solution in https://github.com/pybind/pybind11/issues/1281, the custom exception translator forwards the attributes from the C++ to the Python exception.
This can then be used with regular Python syntax such as:

```python
import sys

sys.path.insert(0, '/home/lars/repos/tudat-bundle/build/tudatpy/')

from tudatpy.exceptions import InterpolationOutOfBoundsError
from tudatpy.math.interpolators import (
    BoundaryInterpolationType, create_one_dimensional_scalar_interpolator,
    linear_interpolation)

interpolation_data = {1:10, 2:20, 3:30, 4:40, 5:50, 6:60, 7:70, 8:80, 9:90, 10:100}
interpolator_settings = linear_interpolation(boundary_interpolation = BoundaryInterpolationType.throw_exception_at_boundary)
interpolator = create_one_dimensional_scalar_interpolator(interpolation_data, interpolator_settings)

try:
    print(interpolator.interpolate(-1))
except InterpolationOutOfBoundsError as exp:
    print(exp)
    print(exp.__class__)
    print(f"{exp.requested_value=}")
    print(f"{exp.lower_bound=}")
    print(f"{exp.upper_bound=}")

```

which prints the following output:

```
Error in interpolator, requesting data point outside of boundaries, requested data at -1 but limit values are 1 and 10
<class 'tudatpy.kernel.exceptions.InterpolationOutOfBoundsError'>
exp.requested_value=-1.0
exp.lower_bound=1.0
exp.upper_bound=10.0
```

**Comment by larshinueber** [comment]
@DominicDirkx I've added the docstrings to the error classes and changed the unit tests, such that they only pass if the TudatError-derived class is thrown (see https://github.com/tudat-team/tudat/pull/297/commits/8cd0640687cc0a6068859e50ed474e8bef0aff9f).
Should the error classes themselves also be tested via unit tests? If so, how? I could only think that for a given input the generated error message is compared to an expected error message, but I don't really see a strong benefit to this. What do you think?

If no unit tests are needed then the PR is ready to review from my side :)

**Comment by DominicDirkx** [comment]
@larshinueber I see this has been ready for review for a while, my apologies for having missed it! I'll do my best to go through it this week.

**Comment by DominicDirkx** [comment]
For the unit tests, I think some tests of catching cases where an exception is thrown, and verifying that the contents of the exception are as expected would be sufficient. There are already a couple of places where this is done in the existing unit tests (but, then with the generic exceptions)

File: include/tudat/math/interpolators/lagrangeInterpolator.h [hunk 1]
```diff
@@ -330,30 +341,34 @@ class LagrangeInterpolator : public OneDimensionalInterpolator< IndependentVaria
 private:
     DependentVariableType performLagrangeBoundaryInterpolation(
             const std::shared_ptr< OneDimensionalInterpolator< IndependentVariableType, DependentVariableType > > boundaryInterpolator,
-            const IndependentVariableType& targetIndependentVariableValue )
+            const IndependentVariableType& targetIndependentVariableValue,
+            const IndependentVariableType& lowerBoundReliableInterval,
+            const IndependentVariableType& upperBoundReliableInterval )
```
Comment (DominicDirkx) [inline include/tudat/math/interpolators/lagrangeInterpolator.h]: You don't need to pass the upper/lower bounds as inputs (these are class members that this function can access)

File: include/tudat/basics/tudatExceptions.h [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+ *    a copy of the license with this file. If not, please or visit:
+ *    http://tudat.tudelft.nl/LICENSE.
+ */
+
+#ifndef TUDAT_EXCEPTIONS_H
+#define TUDAT_EXCEPTIONS_H
+
+#include <iostream>
+#include <string>
+#include <boost/lexical_cast.hpp>
```
Comment (DominicDirkx) [inline include/tudat/basics/tudatExceptions.h]: Using boost::lexical_cast is fine, but is 'heritage code'. Using std::to_string is better in most cases (the fewer dependencies on boost, the better)

File: include/tudat/basics/tudatExceptions.h [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+{
+private:
+public:
+    /// @brief Constructor for one-dimensional interpolation out of bounds error.
+    /// @param requestedValue Requested value which is out of bounds.
+    /// @param lowerBound Value of the lower bound of the interpolation data.
+    /// @param upperBound Value of the upper bound of the interpolation data.
+    InterpolationOutOfBoundsError( const T requestedValue, const T lowerBound, const T upperBound ):
+        exceptions::TudatError( "Error in interpolator, requesting data point outside of boundaries, requested data at " +
+                                boost::lexical_cast< std::string >( requestedValue ) + " but limit values are " +
```
Comment (DominicDirkx) [inline include/tudat/basics/tudatExceptions.h]: If typename T is tudat::Time, the std::to_string may not work, but this implementation (https://stackoverflow.com/questions/36533199/is-specialization-of-stdto-string-for-custom-types-allowed-by-the-c-standard answer by Makers_f).

**Comment by larshinueber** [comment]
@DominicDirkx Thank you for the comments! Will address them later today 👍

**Comment by DominicDirkx** [comment]
I retriggered the unit tests, they all pass now :+1: Something was wrong with the pipeline last time they ran.

File: include/tudat/basics/tudatExceptions.h (hunk 3 above)
Comment (larshinueber) [reply include/tudat/basics/tudatExceptions.h]: That was indeed the issue why I used `boost::lexical_cast` at first 😅 I changed it to cast to `double` first and then use `std::to_string`, which seems to work fine

File: include/tudat/math/interpolators/lagrangeInterpolator.h (hunk 1 above)
Comment (larshinueber) [reply include/tudat/math/interpolators/lagrangeInterpolator.h]: Replaced this to pass the indexes, which are then used to retrieve the reliable interval bounds inside the function.

**Comment by DominicDirkx** [comment]
@larshinueber I see an open action for adding unit tests. There are already a couple of tests of catching exceptions in existing unit tests, I think if you extend those to catch the derived exceptions, the test coverage is good.

**Comment by larshinueber** [comment]
@DominicDirkx I've adapted all the existing unit tests to check if an instance of the specific error class is thrown and if the returned exception stores the expected values. Let know if there is anything to add 👍

**Comment by DominicDirkx** [comment]
Awesome! Let's wait for the CI to finish and, if succesful, I think this can be merged :)

**Comment by DominicDirkx** [comment]
Merged!

**Comment by larshinueber** [comment]
@DominicDirkx Thank you for the reviews and help getting this to work :)
